### ISSUE TITLE
[FR] Allow image cache file location to be specified

### ISSUE THREAD

**Issue by technotherion** [ckt1031/obsidian-tinypng-plugin#1]
I have a folder called '_resources' where I place all of my content that is handled by plugins. It would help to reduce visual clutter since the json file is currently in the root directory along with a bunch of my other files.

**Comment by vonalbert** [comment]
I'm interested too in this feature. I presume @technotherion enabled, like me, the obsidian option to show all your files, not just *.md. Maybe a less invasive way to reduce the visual clutter in the root could be to make the cache file an hidden one by prepending a dot to the name. Obviously the plugin should handle the rename too.

WDYT @ckt1031, @technotherion?

**Comment by ckt1031** [comment]
> I'm interested in this feature too. I presume @technotherion enabled, like me, the obsidian option to show all your files, not just *.md. Maybe a less invasive way to reduce the visual clutter in the root could be to make the cache file an hidden one by prepending a dot to the name. Obviously the plugin should handle the rename too.
> 
> 
> 
> WDYT @ckt1031, @technotherion?

I could add a custom config to set cache folder path, but make sure that folder are synced to avoid redundant API calls.

**Comment by vonalbert** [comment]
That would be perfect for me.
